all:	clean web_server client
web_server:
	gcc -pthread -o web_server web_server.c
client:
	gcc -pthread -o client client.c
clean:
	rm -f web_server client thread_1.log thread_2.log thread_3.log thread_4.log thread_5.log thread_6.log thread_7.log thread_8.log thread_9.log thread_10.log